package com.ahwers.marvin.framework.application.resource.enums;

public enum ResourceRepresentationType {
	
	HTML_APPLICATION_INTERFACE,
	HTML_APPLICATION_INTERFACE_STATE_TRANSFORMATION_JAVASCRIPT_SCRIPT,
	HTML_APPLICATION_INTERFACE_STATE_INSTANTIATION_JAVASCRIPT_SCRIPT,
	COMMAND_OPTION_LIST,
	PLAIN_TEXT,

}
